# Generated by Django 6.0.7 on 2026-08-15 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntityResolutionCache",
            fields=[
                (
                    "query_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("resolved_entities", models.JSONField(default=list)),
                ("resolved_at", models.DateTimeField(auto_now=True)),
                ("ttl_seconds", models.IntegerField(default=2592000)),
            ],
            options={
                "db_table": "entity_resolution_cache",
            },
        ),
        migrations.CreateModel(
            name="TabCard",
            fields=[
                (
                    "url_hash",
                    models.CharField(
                        db_index=True, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.TextField()),
                ("title", models.TextField(blank=True, default="")),
                (
                    "domain",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("pseudo_doc", models.TextField(blank=True, default="")),
                ("main_text", models.TextField(blank=True, default="")),
                ("embedding", models.JSONField(blank=True, null=True)),
                (
                    "extraction_tier",
                    models.CharField(
                        choices=[
                            ("hash_only", "Hash Only"),
                            ("local_ner", "Local NER"),
                            ("llm_enriched", "LLM Enriched"),
                        ],
                        default="local_ner",
                        max_length=30,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now=True)),
                (
                    "last_seen_open_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tab_cards",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="TabEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_name", models.CharField(db_index=True, max_length=255)),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "url_hash",
                    models.ForeignKey(
                        db_column="url_hash",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="api.tabcard",
                    ),
                ),
            ],
            options={
                "db_table": "tab_entities",
                "indexes": [
                    models.Index(
                        fields=["entity_name", "entity_type"],
                        name="tab_entitie_entity__0dfe99_idx",
                    )
                ],
            },
        ),
    ]
